version: '3.7'

services:
  abouttoday:
    image: abouttoday.net:production
    networks:
      - web
    labels:
      - "traefik.frontend.rule=Host:www.abouttoday.net"
      - "traefik.docker.network=traefik_default"
networks:
  web:
    name: traefik_default